language: python
python:
  - "3.9.6"
# command to install dependencies
install:
  - pip install pylint
  - pip install -r requirements.txt
# command to run tests
before_script:
  - make build
  - make lint
script:
  - make test
# safelist
# branches:
#     only:
#     - master
